version: '3'

services:
  app1:
    image: ubuntu:latest
    ports:
      - 8081:8081
    container_name: nginx_exercise_case2_app1
    volumes:
      - ./bin/hello:/bin/hello
    command: /bin/hello -i 1
  app2:
    image: ubuntu:latest
    ports:
      - 8082:8082
    container_name: nginx_exercise_case2_app2
    volumes:
      - ./bin/hello:/bin/hello
    command: /bin/hello -i 2
  app3:
    image: ubuntu:latest
    ports:
      - 8083:8083
    container_name: nginx_exercise_case2_app3
    volumes:
      - ./bin/hello:/bin/hello
    command: /bin/hello -i 3
  server:
    build: .
    ports:
      - 8080:80
    container_name: nginx_exercise_case2_server

networks:
  default:
